[package]
name = "zad5"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
dialoguer = { version = "0.11.0", default-features = false }
num-format = "0.4.4"
statistical = "1.0.0"
getset = "0.1.2"
rayon = "1.10.0"
num = "*"

[profile.dev]
opt-level = 3
